name: photostack

services:
  caddy:
    image: caddy:latest
    container_name: ${CADDY_CONTAINER_NAME:-caddy}
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    environment:
      TS_NODE: "${TS_NODE}"
      PUBLIC_DOMAIN: "${PUBLIC_DOMAIN}"
      IMMICH_PUBLIC_DOMAIN: "${IMMICH_PUBLIC_DOMAIN}"
      PHOTOPRISM_PUBLIC_DOMAIN: "${PHOTOPRISM_PUBLIC_DOMAIN}"
      IMMICH_UPSTREAM: "${IMMICH_UPSTREAM}"
      PHOTOPRISM_UPSTREAM: "${PHOTOPRISM_UPSTREAM}"
    volumes:
      - "${CADDYFILE_TARGET:-./compose/Caddyfile}:/etc/caddy/Caddyfile:ro"
      # Tailscale certs directory on the host; certs named ${TS_NODE}.crt/.key
      - "${CADDY_CERTS_DIR:-$HOME/caddy/certs}:/etc/certs:ro"
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  default:
    name: photo_net
    external: true
