name: watchtower

services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_INCLUDE_RESTARTING: "true"
      # Schedule: 3AM EST = 8AM UTC (cron format: second minute hour day month weekday)
      WATCHTOWER_SCHEDULE: "0 0 8 * * *"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.docker/config.json:/config.json" # optional, for authentication if you have a Docker Hub account

networks:
  default:
    name: photo_net
    external: true
